spring:
  application:
    name: "products-backend-spring"
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  topic:
    name: products
  groupId: product-group-1

security:
  basic:
    username: admin
    password: password

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
